Relax VersionStorageInfo::GetOverlappingInputs check
cockroachdb/rocksdb pull request #4
Opened 2018-07-09 21:27 UTC by petermattis

Do not consider the range tombstone sentinel key as causing 2 adjacent
sstables in a level to overlap. When a range tombstone's end key is the
largest key in an sstable, the sstable's end key is set to a "sentinel"
value that is the smallest key in the next sstable with a sequence
number of kMaxSequenceNumber. This "sentinel" is guaranteed to not
overlap in internal-key space with the next sstable. Unfortunately,
GetOverlappingFiles uses user-keys to determine overlap and was thus
considering 2 adjacent sstables in a level to overlap if they were
separated by this sentinel key. This in turn would cause compactions to
be larger than necessary.

This previous behavior of GetOverlappingInputs was necessary due to the
following scenario:

  * Write a delete range [a, d).
  * After compaction, this deleted range may be added to multiple sst
    files: a.sst, b.sst, c.sst, but the boundaries of these sst files
    are [a, b), [b, c), [c, d).
  * When a.sst and b.sst reach the bottommost level, the delete range of
    the sst files will be dropped.
  * Write a new key in the range [a, c).
  * When the newly written key [a, c) reaches the bottommost level, its
    sequence number will be set to zero.
  * When the front c.sst compacts with the key in the range [a, c) the
    sequence number of that key is zero, and the key will be incorrectly
    dropped.

That scenario no longer occurs because we are truncating range deletion
tombstones to sstable boundaries when adding them to RangeDelAggregator.

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/rocksdb/4)

2018-07-10 11:33 UTC, benesch approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/rocksdb/4#-:-LH2xh5FD4uO3CKRoAwL:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bdarnell)



<!-- Sent from Reviewable.io -->

2018-07-10 19:08 UTC, bdarnell approved these changes
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/rocksdb/4)* status: all files reviewed, 1 unresolved discussion (waiting on @petermattis)

___
*[db/db_range_del_test.cc, line 898 at r1](https://reviewable.io/reviews/cockroachdb/rocksdb/4#-LH4ZF_v0k6bwrzCiKA3:-LH4ZF_v0k6bwrzCiKA4:b-ngobxq) ([raw file](https://github.com/cockroachdb/rocksdb/blob/e8bf45470a4f921228b1aeaa67473298dec3fe46/db/db_range_del_test.cc#L898)):*
> ```cpp
> 
> TEST_F(DBRangeDelTest, CompactionTreatsSplitInputLevelDeletionAtomically) {
>   // make sure compaction treats files containing a split range deletion in the
> ```

The fact that they had a test for this makes me worry that we might be subtly breaking something with this change. I can't tell what that might be, though. 


<!-- Sent from Reviewable.io -->

2018-07-10 19:22 UTC, petermattis reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/rocksdb/4)* status: all files reviewed, 1 unresolved discussion (waiting on @petermattis)

___
*[db/db_range_del_test.cc, line 898 at r1](https://reviewable.io/reviews/cockroachdb/rocksdb/4#-LH4ZF_v0k6bwrzCiKA3:-LH4d1ZdBcW2_ry8KBOa:b3e0mqi) ([raw file](https://github.com/cockroachdb/rocksdb/blob/e8bf45470a4f921228b1aeaa67473298dec3fe46/db/db_range_del_test.cc#L898)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

The fact that they had a test for this makes me worry that we might be subtly breaking something with this change. I can't tell what that might be, though. 
</blockquote></details>

Yes, this is the scariest part of my changes. The scenario is the one described in the commit message and also described in my RocksDB Compactions document. I'm reasonably confident that this change is correct now that sstables are truncated to tombstone boundaries. 


<!-- Sent from Reviewable.io -->

2018-07-10 19:23 UTC, benesch approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/rocksdb/4)* status: all files reviewed, 1 unresolved discussion (waiting on @bdarnell)

___
*[db/db_range_del_test.cc, line 898 at r1](https://reviewable.io/reviews/cockroachdb/rocksdb/4#-LH4ZF_v0k6bwrzCiKA3:-LH4dCH07u9A0ZDioy_M:b-3p4eqq) ([raw file](https://github.com/cockroachdb/rocksdb/blob/e8bf45470a4f921228b1aeaa67473298dec3fe46/db/db_range_del_test.cc#L898)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Yes, this is the scariest part of my changes. The scenario is the one described in the commit message and also described in my RocksDB Compactions document. I'm reasonably confident that this change is correct now that sstables are truncated to tombstone boundaries. 
</blockquote></details>

This was actually [discussed upstream](https://github.com/facebook/rocksdb/pull/4050#issuecomment-400064659). tl;dr it's OK as long as #3 goes in first.


<!-- Sent from Reviewable.io -->

2018-07-11 00:24 UTC, benesch approved these changes
Rebase <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>. Fire away.

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/rocksdb/4#-:-LH5iPvWEgXE1QQEEo06:b-22jawl)* status: all files reviewed, 1 unresolved discussion (waiting on @bdarnell)



<!-- Sent from Reviewable.io -->

2018-07-11 00:29 UTC, petermattis commented
I wonder if I should hold off on merging this PR for a day or two to let the other PRs I just merged settle. Or is it better to rip the bandaid off?

Also, I want @bdarnell to give the thumbs up that the scenario that was previously protected against by treating sstables overlapped by a common range tombstone as an atomic unit is no longer a problem now that tombstones are truncated to sstable boundaries. More specifically, are there similar scenarios to be worried about? I haven't thought of one, but more brains thinking about this can't hurt.

2018-07-11 00:42 UTC, benesch commented
I'm of the opinion that the sooner we get this into Cockroach the sooner we'll find the bugs. If we start seeing keys go missing after compactions we'll know exactly where to look.

I can see the logic in waiting though.

2018-07-11 01:22 UTC, petermattis commented
The CI test failure is:

```
[ RUN      ] DBRangeDelTest.CompactionTreatsSplitInputLevelDeletionAtomically
db_range_del_test: db/version_set.cc:1757: void rocksdb::VersionStorageInfo::AddFile(int, rocksdb::FileMetaData*, rocksdb::Logger*): Assertion `false' failed.
Received signal 6 (Aborted)
#0   /lib/x86_64-linux-gnu/libc.so.6(gsignal+0x37) [0x14c85d367c37] ??	??:0	
#1   /lib/x86_64-linux-gnu/libc.so.6(abort+0x148) [0x14c85d36b028] ??	??:0	
#2   /lib/x86_64-linux-gnu/libc.so.6(+0x2fbf6) [0x14c85d360bf6] ??	??:0	
#3   /lib/x86_64-linux-gnu/libc.so.6(+0x2fca2) [0x14c85d360ca2] ??	??:0	
#4   ./db_range_del_test() [0x677704] rocksdb::VersionStorageInfo::AddFile(int, rocksdb::FileMetaData*, rocksdb::Logger*)	/home/travis/build/cockroachdb/rocksdb/db/version_set.cc:1757	
#5   ./db_range_del_test() [0x6646cf] rocksdb::VersionBuilder::Rep::MaybeAddFile(rocksdb::VersionStorageInfo*, int, rocksdb::FileMetaData*)	/home/travis/build/cockroachdb/rocksdb/db/version_builder.cc:426	
#6   ./db_range_del_test() [0x68165f] Status	/home/travis/build/cockroachdb/rocksdb/./include/rocksdb/status.h:28	
#7   ./db_range_del_test() [0x5b0c80] ~_Vector_base	/usr/include/c++/4.8/bits/stl_vector.h:161	
#8   ./db_range_del_test() [0x5b4ee6] rocksdb::CompactionJob::Install(rocksdb::MutableCFOptions const&)	/home/travis/build/cockroachdb/rocksdb/db/compaction_job.cc:597 (discriminator 1)	
#9   ./db_range_del_test() [0x5ec1e0] rocksdb::DBImpl::BackgroundCompaction(bool*, rocksdb::JobContext*, rocksdb::LogBuffer*, rocksdb::DBImpl::PrepickedCompaction*)	/home/travis/build/cockroachdb/rocksdb/db/db_impl_compaction_flush.cc:1852 (discriminator 1)	
#10  ./db_range_del_test() [0x5f1768] rocksdb::DBImpl::BackgroundCallCompaction(rocksdb::DBImpl::PrepickedCompaction*, rocksdb::Env::Priority)	/home/travis/build/cockroachdb/rocksdb/db/db_impl_compaction_flush.cc:1456	
#11  ./db_range_del_test() [0x5f1dbc] rocksdb::DBImpl::BGWorkCompaction(void*)	/home/travis/build/cockroachdb/rocksdb/db/db_impl_compaction_flush.cc:1273	
#12  ./db_range_del_test() [0x76783a] ~_Function_base	/usr/include/c++/4.8/functional:2029	
#13  ./db_range_del_test() [0x767a5f] rocksdb::ThreadPoolImpl::Impl::BGThreadWrapper(void*)	/home/travis/build/cockroachdb/rocksdb/util/threadpool_imp.cc:304	
#14  /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xb1a60) [0x14c85dcc7a60] ??	??:0	
#15  /lib/x86_64-linux-gnu/libpthread.so.0(+0x8184) [0x14c85e759184] ??	??:0	
#16  /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x14c85d42effd] ??	??:0	
/bin/bash: line 1: 15268 Aborted                 (core dumped) ./$t
make: *** [check_some] Error 1
```

Scary. I'm unable to reproduce it with `./db_range_del_test --gtest_repeat=1000`. I'll dig into this further tomorrow.

2018-07-11 01:38 UTC, bdarnell reviewed
> Assertion `false' failed.

Maybe I should retract my "this is fine" about assertions possibly being disabled :)

> Also, I want @bdarnell to give the thumbs up that the scenario that was previously protected against by treating sstables overlapped by a common range tombstone as an atomic unit is no longer a problem now that tombstones are truncated to sstable boundaries. More specifically, are there similar scenarios to be worried about? I haven't thought of one, but more brains thinking about this can't hurt.

I can't think of anything either, and I'm also in favor of ripping the bandaid off. The one thing that comes to mind is that it might be a performance optimization for some workloads to remember that range tombstones can exceed the bounds of the sstable. If the keyspace affected by the range tombstone remains empty, adding more sstables to the compaction is cheap. But that's clearly not always a sound assumption. 

LGTM aside from the CI failure. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/rocksdb/4#-:-LH5y-xn4WHHR_S3dRQf:b-o2u1fq)* status: all files reviewed, 1 unresolved discussion (waiting on @bdarnell)



<!-- Sent from Reviewable.io -->

2018-07-11 02:06 UTC, benesch commented
> Scary. I'm unable to reproduce it with ./db_range_del_test --gtest_repeat=1000. I'll dig into this further tomorrow.

Are you testing the merge of this branch + master? It's possible it's the integration that's gone wrong.

2018-07-11 02:23 UTC, benesch commented
> Are you testing the merge of this branch + master? It's possible it's the integration that's gone wrong.

Nope, I can't repro it either. I'm rebuilding the failed Travis job with a clean cache.

2018-07-11 02:58 UTC, benesch commented
Welp, same failure. Must be a real bug.

2018-07-11 17:19 UTC, benesch commented
Got a repro on my GCE worker:

```
Adding new file 18 range ('6B6579303030303032' seq:7, type:1, '6B6579303030303034' seq:72057594037927935, type:15) to level 2 but overlapping with existing file 23 '6B6579303030303031' seq:5, type:1 '6B6579303030303032' seq:2, type:15
db_range_del_test: db/version_set.cc:1765: void rocksdb::VersionStorageInfo::AddFile(int, rocksdb::FileMetaData*, rocksdb::Logger*): Assertion `false' failed.
Received signal 6 (Aborted)
#0   /lib/x86_64-linux-gnu/libc.so.6(gsignal+0x38) [0x7f56af2a0428] ??	??:0	
#1   /lib/x86_64-linux-gnu/libc.so.6(abort+0x16a) [0x7f56af2a202a] ??	??:0	
#2   /lib/x86_64-linux-gnu/libc.so.6(+0x2dbd7) [0x7f56af298bd7] ??	??:0	
#3   /lib/x86_64-linux-gnu/libc.so.6(+0x2dc82) [0x7f56af298c82] ??	??:0	
#4   ./db_range_del_test() [0x64d667] rocksdb::VersionStorageInfo::AddFile(int, rocksdb::FileMetaData*, rocksdb::Logger*)	/home/benesch/rocksdb/db/version_set.cc:1765	
#5   ./db_range_del_test() [0x6395ec] rocksdb::VersionBuilder::Rep::MaybeAddFile(rocksdb::VersionStorageInfo*, int, rocksdb::FileMetaData*)	/home/benesch/rocksdb/db/version_builder.cc:426	
#6   ./db_range_del_test() [0x65607e] rocksdb::Status::Status()	/home/benesch/rocksdb/./include/rocksdb/status.h:28	
#7   ./db_range_del_test() [0x570c6f] std::_Vector_base<rocksdb::VersionEdit*, std::allocator<rocksdb::VersionEdit*> >::~_Vector_base()	/usr/include/c++/5/bits/stl_vector.h:161	
#8   ./db_range_del_test() [0x574aa4] rocksdb::Status::operator=(rocksdb::Status&&)	/home/benesch/rocksdb/./include/rocksdb/status.h:306	
#9   ./db_range_del_test() [0x5b14ee] rocksdb::Status::operator=(rocksdb::Status&&)	/home/benesch/rocksdb/./include/rocksdb/status.h:307	
#10  ./db_range_del_test() [0x5b4045] std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_Alloc_hider::_Alloc_hider(char*, std::allocator<char> const&)	/usr/include/c++/5/bits/basic_string.h:109	
#11  ./db_range_del_test() [0x5b479d] rocksdb::DBImpl::BGWorkCompaction(void*)	/home/benesch/rocksdb/db/db_impl_compaction_flush.cc:1273	
#12  ./db_range_del_test() [0x75aa38] std::_Function_base::~_Function_base()	/usr/include/c++/5/functional:1829	
#13  ./db_range_del_test() [0x75ac5b] rocksdb::ThreadPoolImpl::Impl::BGThreadWrapper(void*)	/home/benesch/rocksdb/util/threadpool_imp.cc:304	
#14  /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xb8c80) [0x7f56afc0cc80] ??	??:0	
#15  /lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba) [0x7f56b05076ba] ??	??:0	
#16  /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7f56af37241d] ??	??:0	
Aborted (core dumped)
```

I guess it's macOS vs. Linux or Clang vs GCC.

2018-07-11 21:48 UTC, petermattis commented
This was a real bug. Here's the scenario:

```
L1
  17 [000000#3,1 000002#72057594037927935,15]
L2
  7 [000000#1,1, 000000#1,1]
  18 [000002#7,1, 000004#72057594037927935,15]
```

The compactor decides to compact sstables 17 and 7 together, which produces 2 new sstables:

```
22 [000000#3,1, 000001#72057594037927935,15]
24 [000001#5,1, 000002#2,15]
```

These new sstables reside in L2, which results in the following LSM:

```
L2
  22 [000000#3,1, 000001#72057594037927935,15]
  24 [000001#5,1, 000002#2,15]
  18 [000002#7,1, 000004#72057594037927935,15]
```

Boom! Sstable 24 overlaps with sstable 18. The problem is in determining the boundaries of sstable 24. This occurs in `RangeDelAggregator::AddToBuilder` which is used to add tombstones from the `RangeDelAggregator` to the output file. Since sstable 24 is the last sstable being generated by the compaction, `CompactionJob::FinishCompactionOutputFile` passes `upper_bound == nullptr`. In this case, `RangeDelAggregator::AddToBuilder` was blindly using the range tombstone's end-key as the sstable largest key, but that's incorrect because the tombstone end-key is exclusive, not inclusive. This wasn't previously a problem due to the way sstables containing an overlapping tombstone were treated as an atomic unit.

The fix is simple (1-line). Let's see if there is any fallout. Clearly I need to add a test that exercises this case. I'm still not sure why this happened reliably on Linux, but not on Mac OS X. I did see in my debugging that the test deterministically performed a different set of compactions on Linux vs Mac.

2018-07-11 22:05 UTC, petermattis reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/rocksdb/4)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @bdarnell)

___
*[db/range_del_aggregator.cc, line 608 at r3](https://reviewable.io/reviews/cockroachdb/rocksdb/4#-LHAMvFw17hUf_83t_KJ:-LHAMvFw17hUf_83t_KK:b7xjfa6) ([raw file](https://github.com/cockroachdb/rocksdb/blob/6f0cb406794357b43ce5049adf4ac585d42d364c/db/range_del_aggregator.cc#L608)):*
> ```cpp
>       // file's/subcompaction's smallest key.
>       InternalKey largest_candidate(tombstone.end_key_, kMaxSequenceNumber,
>                                     kTypeRangeDeletion);
> ```

@benesch, @bdarnell this is the 1-line fix (+5 line comment). I'll work on adding a test tomorrow and peruse the code to see if there are more areas where the tombstone end-key is being used inappropriately.


<!-- Sent from Reviewable.io -->

2018-07-11 22:06 UTC, petermattis reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/rocksdb/4)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @bdarnell)

___
*[db/range_del_aggregator.cc, line 608 at r3](https://reviewable.io/reviews/cockroachdb/rocksdb/4#-LHAMvFw17hUf_83t_KJ:-LHANGow2g4yi-VPQ_Nd:b-ff9zjw) ([raw file](https://github.com/cockroachdb/rocksdb/blob/6f0cb406794357b43ce5049adf4ac585d42d364c/db/range_del_aggregator.cc#L608)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

@benesch, @bdarnell this is the 1-line fix (+5 line comment). I'll work on adding a test tomorrow and peruse the code to see if there are more areas where the tombstone end-key is being used inappropriately.
</blockquote></details>

Interestingly, this was the only usage of `RangeTombstone::SerializeEndKey()` in the entire code base. Perhaps safer to adjust that method. 


<!-- Sent from Reviewable.io -->

2018-07-12 05:35 UTC, benesch approved these changes
> Reviewed 1 of 1 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/rocksdb/4)* status: all files reviewed, 2 unresolved discussions (waiting on @bdarnell and @benesch)

___
*[db/range_del_aggregator.cc, line 608 at r3](https://reviewable.io/reviews/cockroachdb/rocksdb/4#-LHAMvFw17hUf_83t_KJ:-LHBz4DT2hOkdQJkA5Zc:b-534cxt) ([raw file](https://github.com/cockroachdb/rocksdb/blob/6f0cb406794357b43ce5049adf4ac585d42d364c/db/range_del_aggregator.cc#L608)):*
> Perhaps safer to adjust that method.

Or just delete it. Either option is fine by me.


<!-- Sent from Reviewable.io -->

2018-07-12 13:46 UTC, petermattis reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/rocksdb/4)* status: 4 of 6 files reviewed, 3 unresolved discussions (waiting on @benesch, @bdarnell, and @petermattis)

___
*[db/db_range_del_test.cc, line 1012 at r5](https://reviewable.io/reviews/cockroachdb/rocksdb/4#-LHDjKeb1kPpQ9XNtTpf:-LHDjKeb1kPpQ9XNtTpg:b-76y1d9) ([raw file](https://github.com/cockroachdb/rocksdb/blob/d816dade9f59db48a2132692b314312bb5a63a05/db/db_range_del_test.cc#L1012)):*
> ```cpp
> TEST_F(DBRangeDelTest, RangeTombstoneEndKeyAsSstableUpperBound) {
>   // Test the handling of the range-tombstone end-key as the
>   // upper-bound for an sstable.
> ```

@benesch, @bdarnell Here is the test which deterministically reproduces the scenario which triggered assertion failure on CI.


<!-- Sent from Reviewable.io -->

2018-07-12 15:43 UTC, benesch requested changes
Sorry, I don't think my brain is working today. I can't figure out how your test corresponds to your diagrams.

> Reviewed 1 of 2 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/rocksdb/4#-:-LHE99D505YbRxr8JqYT:bifouls)* status: all files reviewed, 4 unresolved discussions (waiting on @bdarnell and @petermattis)

___
*[db/db_range_del_test.cc, line 1054 at r6](https://reviewable.io/reviews/cockroachdb/rocksdb/4#-LHE5X61-c4IxgxGy9S1:-LHE5X626Jl64l9-Ebf5:b-mxcnb0) ([raw file](https://github.com/cockroachdb/rocksdb/blob/a68fb65cd0b527b51ca5a102cab0168e1421c2da/db/db_range_del_test.cc#L1054)):*
> ```cpp
>   // Put extra key to trigger final flush.
>   ASSERT_OK(Put("", ""));
>   dbfull()->TEST_WaitForFlushMemTable();
> ```

I'm very confused about this step. So the order of ops is this, right?

```
Put(0)
Put(3)
Put(1)
Put(2)
Flush()
Put("")
Flush()
```

I'm confused about why that creates the SSTs in the diagram?


<!-- Sent from Reviewable.io -->

2018-07-12 16:12 UTC, petermattis reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/rocksdb/4)* status: all files reviewed, 4 unresolved discussions (waiting on @bdarnell and @petermattis)

___
*[db/db_range_del_test.cc, line 1054 at r6](https://reviewable.io/reviews/cockroachdb/rocksdb/4#-LHE5X61-c4IxgxGy9S1:-LHED28I0vtmr6UKOXBk:b3lpbqz) ([raw file](https://github.com/cockroachdb/rocksdb/blob/a68fb65cd0b527b51ca5a102cab0168e1421c2da/db/db_range_del_test.cc#L1054)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

I'm very confused about this step. So the order of ops is this, right?

```
Put(0)
Put(3)
Put(1)
Put(2)
Flush()
Put("")
Flush()
```

I'm confused about why that creates the SSTs in the diagram?
</blockquote></details>

This was borrowed from `CompactionTreatsSplitInputLevelDeletionAtomically`. The keys are put in that strange order so that the L0 tables overlap and thus can't be trivially moved to L1. A key point is that the size of sstables is targeted at `kValueBytes`. So when the L0 -> L1 compaction does occur we create 2 sstables in L1. I've added additional comments to make this clearer.


<!-- Sent from Reviewable.io -->

2018-07-12 18:11 UTC, benesch approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/rocksdb/4#-:-LHEg69c2PbU7SfawH09:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @bdarnell, @petermattis, and @benesch)

___
*[db/db_range_del_test.cc, line 1054 at r6](https://reviewable.io/reviews/cockroachdb/rocksdb/4#-LHE5X61-c4IxgxGy9S1:-LHEGew22mWJiPytyhI8:boshd3u) ([raw file](https://github.com/cockroachdb/rocksdb/blob/a68fb65cd0b527b51ca5a102cab0168e1421c2da/db/db_range_del_test.cc#L1054)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This was borrowed from `CompactionTreatsSplitInputLevelDeletionAtomically`. The keys are put in that strange order so that the L0 tables overlap and thus can't be trivially moved to L1. A key point is that the size of sstables is targeted at `kValueBytes`. So when the L0 -> L1 compaction does occur we create 2 sstables in L1. I've added additional comments to make this clearer.
</blockquote></details>

Ah, thanks for updating the diagram. It makes a lot more sense now.

Still, I'd advocate for this diff to make it clearer what's happening:

```diff
diff --git a/db/db_range_del_test.cc b/db/db_range_del_test.cc
index ea9a7af97..3b0d6095f 100644
--- a/db/db_range_del_test.cc
+++ b/db/db_range_del_test.cc
@@ -1046,14 +1046,10 @@ TEST_F(DBRangeDelTest, RangeTombstoneEndKeyAsSstableUpperBound) {
     // compact from L0 to L1.
     ASSERT_OK(Put(Key(j), value));
     ASSERT_OK(Put(Key(2 * kNumFilesPerLevel - 1 - j), value));
-    if (j > 0) {
-      dbfull()->TEST_WaitForFlushMemTable();
-      ASSERT_EQ(j, NumTableFilesAtLevel(0));
-    }
+    ASSERT_OK(db_->Flush(FlushOptions()));
+    ASSERT_EQ(j + 1, NumTableFilesAtLevel(0));
   }
-  // Put extra key to trigger final flush.
-  ASSERT_OK(Put("", ""));
-  dbfull()->TEST_WaitForFlushMemTable();
+
   // Compact the 2 L0 sstables to L1, resulting in the following LSM. There
   // are 2 sstables generated in L1 due to the target_file_size_base setting.
   //   L1:
```


<!-- Sent from Reviewable.io -->

2018-07-12 18:38 UTC, petermattis reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/rocksdb/4)* status: 5 of 6 files reviewed, 4 unresolved discussions (waiting on @benesch, @bdarnell, and @petermattis)

___
*[db/db_range_del_test.cc, line 898 at r1](https://reviewable.io/reviews/cockroachdb/rocksdb/4#-LH4ZF_v0k6bwrzCiKA3:-LHEmN9h8X6uSDnyGo54:b-896fix) ([raw file](https://github.com/cockroachdb/rocksdb/blob/e8bf45470a4f921228b1aeaa67473298dec3fe46/db/db_range_del_test.cc#L898)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

This was actually [discussed upstream](https://github.com/facebook/rocksdb/pull/4050#issuecomment-400064659). tl;dr it's OK as long as #3 goes in first.
</blockquote></details>

Done.
___
*[db/db_range_del_test.cc, line 1054 at r6](https://reviewable.io/reviews/cockroachdb/rocksdb/4#-LHE5X61-c4IxgxGy9S1:-LHEmK3qAMrqc02kpPVi:b-qqx0w8) ([raw file](https://github.com/cockroachdb/rocksdb/blob/a68fb65cd0b527b51ca5a102cab0168e1421c2da/db/db_range_del_test.cc#L1054)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Ah, thanks for updating the diagram. It makes a lot more sense now.

Still, I'd advocate for this diff to make it clearer what's happening:

```diff
diff --git a/db/db_range_del_test.cc b/db/db_range_del_test.cc
index ea9a7af97..3b0d6095f 100644
--- a/db/db_range_del_test.cc
+++ b/db/db_range_del_test.cc
@@ -1046,14 +1046,10 @@ TEST_F(DBRangeDelTest, RangeTombstoneEndKeyAsSstableUpperBound) {
     // compact from L0 to L1.
     ASSERT_OK(Put(Key(j), value));
     ASSERT_OK(Put(Key(2 * kNumFilesPerLevel - 1 - j), value));
-    if (j > 0) {
-      dbfull()->TEST_WaitForFlushMemTable();
-      ASSERT_EQ(j, NumTableFilesAtLevel(0));
-    }
+    ASSERT_OK(db_->Flush(FlushOptions()));
+    ASSERT_EQ(j + 1, NumTableFilesAtLevel(0));
   }
-  // Put extra key to trigger final flush.
-  ASSERT_OK(Put("", ""));
-  dbfull()->TEST_WaitForFlushMemTable();
+
   // Compact the 2 L0 sstables to L1, resulting in the following LSM. There
   // are 2 sstables generated in L1 due to the target_file_size_base setting.
   //   L1:
```
</blockquote></details>

Done. TFTR!


<!-- Sent from Reviewable.io -->

2018-07-12 18:39 UTC, benesch approved these changes
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/rocksdb/4)* status: all files reviewed, 3 unresolved discussions (waiting on @bdarnell and @petermattis)

___
*[db/db_range_del_test.cc, line 1054 at r6](https://reviewable.io/reviews/cockroachdb/rocksdb/4#-LHE5X61-c4IxgxGy9S1:-LHEmZUE9RprLJt9TRkb:b-h4rl6g) ([raw file](https://github.com/cockroachdb/rocksdb/blob/a68fb65cd0b527b51ca5a102cab0168e1421c2da/db/db_range_del_test.cc#L1054)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Done. TFTR!
</blockquote></details>

Of course! Thanks for dealing with my thick skull.


<!-- Sent from Reviewable.io -->

2018-07-12 19:33 UTC, merged